"""empty message

Revision ID: 656a188e6c6c
Revises: 98235ad961a0
Create Date: 2021-01-31 19:25:17.352627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656a188e6c6c'
down_revision = '98235ad961a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('add_date', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(length=1054), nullable=False),
    sa.Column('type', sa.String(length=1054), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_id'), 'error', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_error_id'), table_name='error')
    op.drop_table('error')
    # ### end Alembic commands ###
