"""empty message

Revision ID: 98235ad961a0
Revises: 
Create Date: 2021-01-31 19:06:11.694933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98235ad961a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
