"""empty message

Revision ID: fd47f29954c2
Revises: 
Create Date: 2021-01-11 20:05:04.265659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd47f29954c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpioinput',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('add_date', sa.DateTime(), nullable=True),
    sa.Column('pin', sa.Integer(), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gpioinput_id'), 'gpioinput', ['id'], unique=False)
    op.create_index(op.f('ix_gpioinput_pin'), 'gpioinput', ['pin'], unique=True)
    op.create_table('plant',
    sa.Column('add_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_id'), 'plant', ['id'], unique=False)
    op.create_index(op.f('ix_plant_name'), 'plant', ['name'], unique=False)
    op.create_table('sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('add_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_id'), 'sensor', ['id'], unique=False)
    op.create_index(op.f('ix_sensor_name'), 'sensor', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_name'), table_name='sensor')
    op.drop_index(op.f('ix_sensor_id'), table_name='sensor')
    op.drop_table('sensor')
    op.drop_index(op.f('ix_plant_name'), table_name='plant')
    op.drop_index(op.f('ix_plant_id'), table_name='plant')
    op.drop_table('plant')
    op.drop_index(op.f('ix_gpioinput_pin'), table_name='gpioinput')
    op.drop_index(op.f('ix_gpioinput_id'), table_name='gpioinput')
    op.drop_table('gpioinput')
    # ### end Alembic commands ###
